### PR TITLE
Fix README parts for Wheatley

### LINKED ISSUE #178: README fixes
- [ ] table in Wheatley section doesn't work
- [ ] add instructions for setting which environment variables to what

@kneasle

### PR DESCRIPTION
**Pull request by kneasle**
Fixes #178.

### CODE REVIEW

**Comment by kneasle** [comment]
Is this what you were after with help setting environment variables?  Environment variables are quite standard ways of configuring software, so I'm not sure whether it's really necessary to have it in the README.

It's up to you though.

**Comment by BrynMarieR** [comment]
I don't think it needs to tell you how to set an environment variable, but it should tell you which two env vars need to be set (user doing set up should not need to read the code) and where they should point (directory vs specific startup file, e.g.)

**Comment by kneasle** [comment]
Ah OK that makes more sense - in that case I'll probably remove the explanation of how to set env vars.

What do you think of the new layout for the environment vars?  The `RR_WHEATLEY_PATH` probably could do with a bit more explanation - I'll do that after some revision.

**Comment by BrynMarieR** [comment]
That looks good to me!

**Comment by kneasle** [comment]
OK I think this should be good now?

**Pull request merged**
