### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by mxpidd**
Basic motion controller functionality implemented and help updated. 
A local implementation so no overarching ON/OFF switch or options remembered.

### CODE REVIEW

**Comment by lelandpaul** [comment]
Hi, Mike — this look great so far! I just had a bit of a test and it worked perfectly, first try. Here are the things I think we can improve:

1. Right now, all the code is just native JS attached to the window; the rest of the app, though, is written in the Vue framework and takes advantage of Vue components to encapsulate the code.
2. Regarding the user interface: I'd like to integrate this a bit better into the current tower controls. I think it should have it's own Card object (like the Users box) that only appears if there is a controller connected.
3. Minor nitpick: I don't like using a modifier key like Ctrl as a toggle; I'll have a think about what would work better.

I'll have a bit of a go at implementing some of these changes this weekend. I'm excited, though — this seems to work quite well already!

**Comment by mxpidd** [comment]
Hi Leland,

I’m glad it is looking ok. 

1. I agree that the pure JavaScript approach isn’t ideal. I know nothing of the Vue framework but did struggle to implement as closely as I’d like. If you could support by way of an initial implementation I’ll be able to see how it integrates and use it as a template for further changes.

2. Generally 1. above applies. A separate note will be needed somewhere to point out that it might take a controller button press for gamepads to be recognised.

I do think that if I can get the mobile device implementation working well there could be a big take up from tower bell users. A physical mechanism to distinguish handstroke and backstroke could be very helpful as well as being able to sit back a bit.

3. I liked the idea of using Ctrl for controllers but appreciate your point. It isn’t something I feel strongly about so entirely up to you.

**Comment by lelandpaul** [comment]
Ok — this is a *very preliminary* move to using Vue components. It *nearly* works:
- Controllers are detected and will trigger ringing successfully
- The same status text is printed
- However, W & Ctrl are currently not functional — they both trigger the text to change but don't actually have any effect.

I'll keep poking at this. I think this is really exciting! I've only started consistently using the ActionXL controllers myself in the last few weeks, but I agree having physical handstroke/backstroke makes a huge difference.

**Comment by mxpidd** [comment]
Now working, swap was working, but getting reset every second. Similarly controllers were being looked for and started up every second despite getting turned off.

**Comment by mxpidd** [comment]
I'll have a look at the text tomorrow and see if I can create a text box for the controllers. 

I got a bit sidetracked today when I had a thought. If I can load RR on a phone and access it's accelerometer output then I have a working controller. To use a PC with it I'd just go to a listen room. Two phones not a problem, just allocate to different bells. Are there any issues accessing deviceMotionEvent.accelerationIncludingGravity in Vue?

**Comment by lelandpaul** [comment]
I had a spare bit of time so I went ahead and moved things into a card! There's still some visual tweaking to do, but I think this is a pretty good start.

Re: accelerometers: I don't see any reason we wouldn't be able to access `deviceMotionEvent` from inside Vue. Have a go at it! It might be worth making that it's own pull-request, though: I think it's a separate enough piece of functionality that it would be good to test it separately.

**Comment by mxpidd** [comment]
I've resolved a couple of issues and made some minor changes to buttons & text. I haven't changed the shortcut keys for swap and on/off.

**Comment by kneasle** [comment]
Would it be possible to reformat the JS before merging to have 4 spaces of indentation?

I'm aware it's a bit nitpicky, but formatting consistency makes a huge difference when reading and maintaining code, to the degree that almost all new languages like go and rust come with a built-in formatter (rustfmt and gofmt respectively).  I'm not really bothered about what the style is, so long as everything is consistent.

**Comment by lelandpaul** [comment]
@mxpidd Looks great! Thanks for doing this. I want to tweak a few more things, but I think this is a great improvement.

@kneasle Yes, I'm planning on doing a full code clean-up (including prettify) before this gets merged. I'm also hoping to refactor a lot of the JS before too long to be more maintainable... but that'll be a separate project.

**Comment by kneasle** [comment]
> @kneasle I'm also hoping to refactor a lot of the JS before too long to be more maintainable... but that'll be a separate project.

Cool! The server code is also in need of some TLC, I think (at least it was a challenge to get my head round all the idiosyncrasies when trying to get Wheatley working). But more refactoring the better as far as I'm concerned - and even just rewriting some of the JS would be a massive improvement.

On that note, what happened to the code review thing that was being mooted a while back? I still have #170 open about it (perhaps that scared you off doing it :laughing:). I'd be happy to do some of the grunt refactoring for that - I quite enjoy refactoring in a strange zen kind of way. Imo it would be worth doing a review of the code before embarking on any refactoring.

**Comment by lelandpaul** [comment]
@kneasle Yup — a code review would still be a great idea! I haven't had the spoons for it, but I do think we should get to it soon.

**Comment by lelandpaul** [comment]
Ok! I've tweaked the UI for this to a point where I'm happy with it, and am going to merge. @mxpidd, thanks for all your help on this! I'll probably wind up simplifying some of the code soon, but I'm trying to get a beta out today and I want this included.

**Comment by kneasle** [comment]
> @kneasle Yup — a code review would still be a great idea! I haven't had the spoons for it, but I do think we should get to it soon.

Cool! I'd be happy to help with refactoring when you decide to do it. No hurry though :grin:.

**Pull request merged**
